// AUTO-GENERATED — do not edit manually.
// Source: @octokit/webhooks-types@7.6.1 EventPayloadMap
// Generated: 2026-03-18
// Regenerate: pnpm gen:github

import type { EventDefinition } from "../define";

export const githubEventTypes = [
  "branch_protection_configuration",
  "branch_protection_configuration.disabled",
  "branch_protection_configuration.enabled",
  "branch_protection_rule",
  "branch_protection_rule.created",
  "branch_protection_rule.deleted",
  "branch_protection_rule.edited",
  "check_run",
  "check_run.completed",
  "check_run.created",
  "check_run.requested_action",
  "check_run.rerequested",
  "check_suite",
  "check_suite.completed",
  "check_suite.requested",
  "check_suite.rerequested",
  "code_scanning_alert",
  "code_scanning_alert.appeared_in_branch",
  "code_scanning_alert.closed_by_user",
  "code_scanning_alert.created",
  "code_scanning_alert.fixed",
  "code_scanning_alert.reopened",
  "code_scanning_alert.reopened_by_user",
  "commit_comment",
  "commit_comment.created",
  "create",
  "custom_property",
  "custom_property.created",
  "custom_property.deleted",
  "custom_property_values",
  "custom_property_values.updated",
  "delete",
  "dependabot_alert",
  "dependabot_alert.created",
  "dependabot_alert.dismissed",
  "dependabot_alert.fixed",
  "dependabot_alert.reintroduced",
  "dependabot_alert.reopened",
  "deploy_key",
  "deploy_key.created",
  "deploy_key.deleted",
  "deployment",
  "deployment.created",
  "deployment_protection_rule",
  "deployment_protection_rule.requested",
  "deployment_review",
  "deployment_review.approved",
  "deployment_review.rejected",
  "deployment_review.requested",
  "deployment_status",
  "deployment_status.created",
  "discussion",
  "discussion.answered",
  "discussion.category_changed",
  "discussion.created",
  "discussion.deleted",
  "discussion.edited",
  "discussion.labeled",
  "discussion.locked",
  "discussion.pinned",
  "discussion.transferred",
  "discussion.unanswered",
  "discussion.unlabeled",
  "discussion.unlocked",
  "discussion.unpinned",
  "discussion_comment",
  "discussion_comment.created",
  "discussion_comment.deleted",
  "discussion_comment.edited",
  "fork",
  "github_app_authorization",
  "github_app_authorization.revoked",
  "gollum",
  "installation",
  "installation.created",
  "installation.deleted",
  "installation.new_permissions_accepted",
  "installation.suspend",
  "installation.unsuspend",
  "installation_repositories",
  "installation_repositories.added",
  "installation_repositories.removed",
  "installation_target",
  "installation_target.renamed",
  "issue_comment",
  "issue_comment.created",
  "issue_comment.deleted",
  "issue_comment.edited",
  "issues",
  "issues.assigned",
  "issues.closed",
  "issues.deleted",
  "issues.demilestoned",
  "issues.edited",
  "issues.labeled",
  "issues.locked",
  "issues.milestoned",
  "issues.opened",
  "issues.pinned",
  "issues.reopened",
  "issues.transferred",
  "issues.unassigned",
  "issues.unlabeled",
  "issues.unlocked",
  "issues.unpinned",
  "label",
  "label.created",
  "label.deleted",
  "label.edited",
  "marketplace_purchase",
  "marketplace_purchase.cancelled",
  "marketplace_purchase.changed",
  "marketplace_purchase.pending_change",
  "marketplace_purchase.pending_change_cancelled",
  "marketplace_purchase.purchased",
  "member",
  "member.added",
  "member.edited",
  "member.removed",
  "membership",
  "membership.added",
  "membership.removed",
  "merge_group",
  "merge_group.checks_requested",
  "merge_group.destroyed",
  "meta",
  "meta.deleted",
  "milestone",
  "milestone.closed",
  "milestone.created",
  "milestone.deleted",
  "milestone.edited",
  "milestone.opened",
  "org_block",
  "org_block.blocked",
  "org_block.unblocked",
  "organization",
  "organization.deleted",
  "organization.member_added",
  "organization.member_invited",
  "organization.member_removed",
  "organization.renamed",
  "package",
  "package.published",
  "package.updated",
  "page_build",
  "ping",
  "project",
  "project.closed",
  "project.created",
  "project.deleted",
  "project.edited",
  "project.reopened",
  "project_card",
  "project_card.converted",
  "project_card.created",
  "project_card.deleted",
  "project_card.edited",
  "project_card.moved",
  "project_column",
  "project_column.created",
  "project_column.deleted",
  "project_column.edited",
  "project_column.moved",
  "projects_v2_item",
  "projects_v2_item.archived",
  "projects_v2_item.converted",
  "projects_v2_item.created",
  "projects_v2_item.deleted",
  "projects_v2_item.edited",
  "projects_v2_item.reordered",
  "projects_v2_item.restored",
  "public",
  "pull_request",
  "pull_request.assigned",
  "pull_request.auto_merge_disabled",
  "pull_request.auto_merge_enabled",
  "pull_request.closed",
  "pull_request.converted_to_draft",
  "pull_request.demilestoned",
  "pull_request.dequeued",
  "pull_request.edited",
  "pull_request.enqueued",
  "pull_request.labeled",
  "pull_request.locked",
  "pull_request.milestoned",
  "pull_request.opened",
  "pull_request.ready_for_review",
  "pull_request.reopened",
  "pull_request.review_request_removed",
  "pull_request.review_requested",
  "pull_request.synchronize",
  "pull_request.unassigned",
  "pull_request.unlabeled",
  "pull_request.unlocked",
  "pull_request_review",
  "pull_request_review.dismissed",
  "pull_request_review.edited",
  "pull_request_review.submitted",
  "pull_request_review_comment",
  "pull_request_review_comment.created",
  "pull_request_review_comment.deleted",
  "pull_request_review_comment.edited",
  "pull_request_review_thread",
  "pull_request_review_thread.resolved",
  "pull_request_review_thread.unresolved",
  "push",
  "registry_package",
  "registry_package.published",
  "registry_package.updated",
  "release",
  "release.created",
  "release.deleted",
  "release.edited",
  "release.prereleased",
  "release.published",
  "release.released",
  "release.unpublished",
  "repository",
  "repository.archived",
  "repository.created",
  "repository.deleted",
  "repository.edited",
  "repository.privatized",
  "repository.publicized",
  "repository.renamed",
  "repository.transferred",
  "repository.unarchived",
  "repository_dispatch",
  "repository_import",
  "repository_vulnerability_alert",
  "repository_vulnerability_alert.create",
  "repository_vulnerability_alert.dismiss",
  "repository_vulnerability_alert.reopen",
  "repository_vulnerability_alert.resolve",
  "secret_scanning_alert",
  "secret_scanning_alert.created",
  "secret_scanning_alert.reopened",
  "secret_scanning_alert.resolved",
  "secret_scanning_alert.revoked",
  "secret_scanning_alert_location",
  "secret_scanning_alert_location.created",
  "security_advisory",
  "security_advisory.performed",
  "security_advisory.published",
  "security_advisory.updated",
  "security_advisory.withdrawn",
  "sponsorship",
  "sponsorship.cancelled",
  "sponsorship.created",
  "sponsorship.edited",
  "sponsorship.pending_cancellation",
  "sponsorship.pending_tier_change",
  "sponsorship.tier_changed",
  "star",
  "star.created",
  "star.deleted",
  "status",
  "team",
  "team.added_to_repository",
  "team.created",
  "team.deleted",
  "team.edited",
  "team.removed_from_repository",
  "team_add",
  "watch",
  "watch.started",
  "workflow_dispatch",
  "workflow_job",
  "workflow_job.completed",
  "workflow_job.in_progress",
  "workflow_job.queued",
  "workflow_job.waiting",
  "workflow_run",
  "workflow_run.completed",
  "workflow_run.in_progress",
  "workflow_run.requested",
] as const;

export type GitHubEventType = (typeof githubEventTypes)[number];

/** Auto-generated base descriptions. Hand-curated entries in github/index.ts override these. */
export const generatedGitHubEvents: Record<GitHubEventType, string | EventDefinition> = {
  "branch_protection_configuration": { description: "Branch Protection Configuration", category: "security" },
  "branch_protection_configuration.disabled": { description: "Branch Protection Configuration disabled", category: "security" },
  "branch_protection_configuration.enabled": { description: "Branch Protection Configuration enabled", category: "security" },
  "branch_protection_rule": { description: "Branch Protection Rule", category: "security" },
  "branch_protection_rule.created": { description: "Branch Protection Rule created", category: "security" },
  "branch_protection_rule.deleted": { description: "Branch Protection Rule deleted", category: "security" },
  "branch_protection_rule.edited": { description: "Branch Protection Rule edited", category: "security" },
  "check_run": { description: "Check Run", category: "ci" },
  "check_run.completed": { description: "Check Run completed", category: "ci" },
  "check_run.created": { description: "Check Run created", category: "ci" },
  "check_run.requested_action": { description: "Check Run requested action", category: "ci" },
  "check_run.rerequested": { description: "Check Run rerequested", category: "ci" },
  "check_suite": { description: "Check Suite", category: "ci" },
  "check_suite.completed": { description: "Check Suite completed", category: "ci" },
  "check_suite.requested": { description: "Check Suite requested", category: "ci" },
  "check_suite.rerequested": { description: "Check Suite rerequested", category: "ci" },
  "code_scanning_alert": { description: "Code Scanning Alert", category: "security" },
  "code_scanning_alert.appeared_in_branch": { description: "Code Scanning Alert appeared in branch", category: "security" },
  "code_scanning_alert.closed_by_user": { description: "Code Scanning Alert closed by user", category: "security" },
  "code_scanning_alert.created": { description: "Code Scanning Alert created", category: "security" },
  "code_scanning_alert.fixed": { description: "Code Scanning Alert fixed", category: "security" },
  "code_scanning_alert.reopened": { description: "Code Scanning Alert reopened", category: "security" },
  "code_scanning_alert.reopened_by_user": { description: "Code Scanning Alert reopened by user", category: "security" },
  "commit_comment": { description: "Commit Comment", category: "code" },
  "commit_comment.created": { description: "Commit Comment created", category: "code" },
  "create": { description: "Create", category: "code" },
  "custom_property": { description: "Custom Property", category: "admin" },
  "custom_property.created": { description: "Custom Property created", category: "admin" },
  "custom_property.deleted": { description: "Custom Property deleted", category: "admin" },
  "custom_property_values": { description: "Custom Property Values", category: "admin" },
  "custom_property_values.updated": { description: "Custom Property Values updated", category: "admin" },
  "delete": { description: "Delete", category: "code" },
  "dependabot_alert": { description: "Dependabot Alert", category: "security" },
  "dependabot_alert.created": { description: "Dependabot Alert created", category: "security" },
  "dependabot_alert.dismissed": { description: "Dependabot Alert dismissed", category: "security" },
  "dependabot_alert.fixed": { description: "Dependabot Alert fixed", category: "security" },
  "dependabot_alert.reintroduced": { description: "Dependabot Alert reintroduced", category: "security" },
  "dependabot_alert.reopened": { description: "Dependabot Alert reopened", category: "security" },
  "deploy_key": { description: "Deploy Key", category: "deployments" },
  "deploy_key.created": { description: "Deploy Key created", category: "deployments" },
  "deploy_key.deleted": { description: "Deploy Key deleted", category: "deployments" },
  "deployment": { description: "Deployment", category: "deployments" },
  "deployment.created": { description: "Deployment created", category: "deployments" },
  "deployment_protection_rule": { description: "Deployment Protection Rule", category: "deployments" },
  "deployment_protection_rule.requested": { description: "Deployment Protection Rule requested", category: "deployments" },
  "deployment_review": { description: "Deployment Review", category: "deployments" },
  "deployment_review.approved": { description: "Deployment Review approved", category: "deployments" },
  "deployment_review.rejected": { description: "Deployment Review rejected", category: "deployments" },
  "deployment_review.requested": { description: "Deployment Review requested", category: "deployments" },
  "deployment_status": { description: "Deployment Status", category: "deployments" },
  "deployment_status.created": { description: "Deployment Status created", category: "deployments" },
  "discussion": { description: "Discussion", category: "community" },
  "discussion.answered": { description: "Discussion answered", category: "community" },
  "discussion.category_changed": { description: "Discussion category changed", category: "community" },
  "discussion.created": { description: "Discussion created", category: "community" },
  "discussion.deleted": { description: "Discussion deleted", category: "community" },
  "discussion.edited": { description: "Discussion edited", category: "community" },
  "discussion.labeled": { description: "Discussion labeled", category: "community" },
  "discussion.locked": { description: "Discussion locked", category: "community" },
  "discussion.pinned": { description: "Discussion pinned", category: "community" },
  "discussion.transferred": { description: "Discussion transferred", category: "community" },
  "discussion.unanswered": { description: "Discussion unanswered", category: "community" },
  "discussion.unlabeled": { description: "Discussion unlabeled", category: "community" },
  "discussion.unlocked": { description: "Discussion unlocked", category: "community" },
  "discussion.unpinned": { description: "Discussion unpinned", category: "community" },
  "discussion_comment": { description: "Discussion Comment", category: "community" },
  "discussion_comment.created": { description: "Discussion Comment created", category: "community" },
  "discussion_comment.deleted": { description: "Discussion Comment deleted", category: "community" },
  "discussion_comment.edited": { description: "Discussion Comment edited", category: "community" },
  "fork": { description: "Fork", category: "social" },
  "github_app_authorization": { description: "Github App Authorization", category: "apps" },
  "github_app_authorization.revoked": { description: "Github App Authorization revoked", category: "apps" },
  "gollum": { description: "Gollum", category: "code" },
  "installation": { description: "Installation", category: "apps" },
  "installation.created": { description: "Installation created", category: "apps" },
  "installation.deleted": { description: "Installation deleted", category: "apps" },
  "installation.new_permissions_accepted": { description: "Installation new permissions accepted", category: "apps" },
  "installation.suspend": { description: "Installation suspend", category: "apps" },
  "installation.unsuspend": { description: "Installation unsuspend", category: "apps" },
  "installation_repositories": { description: "Installation Repositories", category: "apps" },
  "installation_repositories.added": { description: "Installation Repositories added", category: "apps" },
  "installation_repositories.removed": { description: "Installation Repositories removed", category: "apps" },
  "installation_target": { description: "Installation Target", category: "apps" },
  "installation_target.renamed": { description: "Installation Target renamed", category: "apps" },
  "issue_comment": { description: "Issue Comment", category: "issues" },
  "issue_comment.created": { description: "Issue Comment created", category: "issues" },
  "issue_comment.deleted": { description: "Issue Comment deleted", category: "issues" },
  "issue_comment.edited": { description: "Issue Comment edited", category: "issues" },
  "issues": { description: "Issues", category: "issues" },
  "issues.assigned": { description: "Issues assigned", category: "issues" },
  "issues.closed": { description: "Issues closed", category: "issues" },
  "issues.deleted": { description: "Issues deleted", category: "issues" },
  "issues.demilestoned": { description: "Issues demilestoned", category: "issues" },
  "issues.edited": { description: "Issues edited", category: "issues" },
  "issues.labeled": { description: "Issues labeled", category: "issues" },
  "issues.locked": { description: "Issues locked", category: "issues" },
  "issues.milestoned": { description: "Issues milestoned", category: "issues" },
  "issues.opened": { description: "Issues opened", category: "issues" },
  "issues.pinned": { description: "Issues pinned", category: "issues" },
  "issues.reopened": { description: "Issues reopened", category: "issues" },
  "issues.transferred": { description: "Issues transferred", category: "issues" },
  "issues.unassigned": { description: "Issues unassigned", category: "issues" },
  "issues.unlabeled": { description: "Issues unlabeled", category: "issues" },
  "issues.unlocked": { description: "Issues unlocked", category: "issues" },
  "issues.unpinned": { description: "Issues unpinned", category: "issues" },
  "label": { description: "Label", category: "admin" },
  "label.created": { description: "Label created", category: "admin" },
  "label.deleted": { description: "Label deleted", category: "admin" },
  "label.edited": { description: "Label edited", category: "admin" },
  "marketplace_purchase": { description: "Marketplace Purchase", category: "marketplace" },
  "marketplace_purchase.cancelled": { description: "Marketplace Purchase cancelled", category: "marketplace" },
  "marketplace_purchase.changed": { description: "Marketplace Purchase changed", category: "marketplace" },
  "marketplace_purchase.pending_change": { description: "Marketplace Purchase pending change", category: "marketplace" },
  "marketplace_purchase.pending_change_cancelled": { description: "Marketplace Purchase pending change cancelled", category: "marketplace" },
  "marketplace_purchase.purchased": { description: "Marketplace Purchase purchased", category: "marketplace" },
  "member": { description: "Member", category: "admin" },
  "member.added": { description: "Member added", category: "admin" },
  "member.edited": { description: "Member edited", category: "admin" },
  "member.removed": { description: "Member removed", category: "admin" },
  "membership": { description: "Membership", category: "admin" },
  "membership.added": { description: "Membership added", category: "admin" },
  "membership.removed": { description: "Membership removed", category: "admin" },
  "merge_group": { description: "Merge Group", category: "code" },
  "merge_group.checks_requested": { description: "Merge Group checks requested", category: "code" },
  "merge_group.destroyed": { description: "Merge Group destroyed", category: "code" },
  "meta": { description: "Meta", category: "system" },
  "meta.deleted": { description: "Meta deleted", category: "system" },
  "milestone": { description: "Milestone", category: "issues" },
  "milestone.closed": { description: "Milestone closed", category: "issues" },
  "milestone.created": { description: "Milestone created", category: "issues" },
  "milestone.deleted": { description: "Milestone deleted", category: "issues" },
  "milestone.edited": { description: "Milestone edited", category: "issues" },
  "milestone.opened": { description: "Milestone opened", category: "issues" },
  "org_block": { description: "Org Block", category: "admin" },
  "org_block.blocked": { description: "Org Block blocked", category: "admin" },
  "org_block.unblocked": { description: "Org Block unblocked", category: "admin" },
  "organization": { description: "Organization", category: "admin" },
  "organization.deleted": { description: "Organization deleted", category: "admin" },
  "organization.member_added": { description: "Organization member added", category: "admin" },
  "organization.member_invited": { description: "Organization member invited", category: "admin" },
  "organization.member_removed": { description: "Organization member removed", category: "admin" },
  "organization.renamed": { description: "Organization renamed", category: "admin" },
  "package": { description: "Package", category: "packages" },
  "package.published": { description: "Package published", category: "packages" },
  "package.updated": { description: "Package updated", category: "packages" },
  "page_build": { description: "Page Build", category: "pages" },
  "ping": { description: "Ping", category: "system" },
  "project": { description: "Project", category: "projects" },
  "project.closed": { description: "Project closed", category: "projects" },
  "project.created": { description: "Project created", category: "projects" },
  "project.deleted": { description: "Project deleted", category: "projects" },
  "project.edited": { description: "Project edited", category: "projects" },
  "project.reopened": { description: "Project reopened", category: "projects" },
  "project_card": { description: "Project Card", category: "projects" },
  "project_card.converted": { description: "Project Card converted", category: "projects" },
  "project_card.created": { description: "Project Card created", category: "projects" },
  "project_card.deleted": { description: "Project Card deleted", category: "projects" },
  "project_card.edited": { description: "Project Card edited", category: "projects" },
  "project_card.moved": { description: "Project Card moved", category: "projects" },
  "project_column": { description: "Project Column", category: "projects" },
  "project_column.created": { description: "Project Column created", category: "projects" },
  "project_column.deleted": { description: "Project Column deleted", category: "projects" },
  "project_column.edited": { description: "Project Column edited", category: "projects" },
  "project_column.moved": { description: "Project Column moved", category: "projects" },
  "projects_v2_item": { description: "Projects V2 Item", category: "projects" },
  "projects_v2_item.archived": { description: "Projects V2 Item archived", category: "projects" },
  "projects_v2_item.converted": { description: "Projects V2 Item converted", category: "projects" },
  "projects_v2_item.created": { description: "Projects V2 Item created", category: "projects" },
  "projects_v2_item.deleted": { description: "Projects V2 Item deleted", category: "projects" },
  "projects_v2_item.edited": { description: "Projects V2 Item edited", category: "projects" },
  "projects_v2_item.reordered": { description: "Projects V2 Item reordered", category: "projects" },
  "projects_v2_item.restored": { description: "Projects V2 Item restored", category: "projects" },
  "public": { description: "Public", category: "admin" },
  "pull_request": { description: "Pull Request", category: "code" },
  "pull_request.assigned": { description: "Pull Request assigned", category: "code" },
  "pull_request.auto_merge_disabled": { description: "Pull Request auto merge disabled", category: "code" },
  "pull_request.auto_merge_enabled": { description: "Pull Request auto merge enabled", category: "code" },
  "pull_request.closed": { description: "Pull Request closed", category: "code" },
  "pull_request.converted_to_draft": { description: "Pull Request converted to draft", category: "code" },
  "pull_request.demilestoned": { description: "Pull Request demilestoned", category: "code" },
  "pull_request.dequeued": { description: "Pull Request dequeued", category: "code" },
  "pull_request.edited": { description: "Pull Request edited", category: "code" },
  "pull_request.enqueued": { description: "Pull Request enqueued", category: "code" },
  "pull_request.labeled": { description: "Pull Request labeled", category: "code" },
  "pull_request.locked": { description: "Pull Request locked", category: "code" },
  "pull_request.milestoned": { description: "Pull Request milestoned", category: "code" },
  "pull_request.opened": { description: "Pull Request opened", category: "code" },
  "pull_request.ready_for_review": { description: "Pull Request ready for review", category: "code" },
  "pull_request.reopened": { description: "Pull Request reopened", category: "code" },
  "pull_request.review_request_removed": { description: "Pull Request review request removed", category: "code" },
  "pull_request.review_requested": { description: "Pull Request review requested", category: "code" },
  "pull_request.synchronize": { description: "Pull Request synchronize", category: "code" },
  "pull_request.unassigned": { description: "Pull Request unassigned", category: "code" },
  "pull_request.unlabeled": { description: "Pull Request unlabeled", category: "code" },
  "pull_request.unlocked": { description: "Pull Request unlocked", category: "code" },
  "pull_request_review": { description: "Pull Request Review", category: "code" },
  "pull_request_review.dismissed": { description: "Pull Request Review dismissed", category: "code" },
  "pull_request_review.edited": { description: "Pull Request Review edited", category: "code" },
  "pull_request_review.submitted": { description: "Pull Request Review submitted", category: "code" },
  "pull_request_review_comment": { description: "Pull Request Review Comment", category: "code" },
  "pull_request_review_comment.created": { description: "Pull Request Review Comment created", category: "code" },
  "pull_request_review_comment.deleted": { description: "Pull Request Review Comment deleted", category: "code" },
  "pull_request_review_comment.edited": { description: "Pull Request Review Comment edited", category: "code" },
  "pull_request_review_thread": { description: "Pull Request Review Thread", category: "code" },
  "pull_request_review_thread.resolved": { description: "Pull Request Review Thread resolved", category: "code" },
  "pull_request_review_thread.unresolved": { description: "Pull Request Review Thread unresolved", category: "code" },
  "push": { description: "Push", category: "code" },
  "registry_package": { description: "Registry Package", category: "packages" },
  "registry_package.published": { description: "Registry Package published", category: "packages" },
  "registry_package.updated": { description: "Registry Package updated", category: "packages" },
  "release": { description: "Release", category: "releases" },
  "release.created": { description: "Release created", category: "releases" },
  "release.deleted": { description: "Release deleted", category: "releases" },
  "release.edited": { description: "Release edited", category: "releases" },
  "release.prereleased": { description: "Release prereleased", category: "releases" },
  "release.published": { description: "Release published", category: "releases" },
  "release.released": { description: "Release released", category: "releases" },
  "release.unpublished": { description: "Release unpublished", category: "releases" },
  "repository": { description: "Repository", category: "admin" },
  "repository.archived": { description: "Repository archived", category: "admin" },
  "repository.created": { description: "Repository created", category: "admin" },
  "repository.deleted": { description: "Repository deleted", category: "admin" },
  "repository.edited": { description: "Repository edited", category: "admin" },
  "repository.privatized": { description: "Repository privatized", category: "admin" },
  "repository.publicized": { description: "Repository publicized", category: "admin" },
  "repository.renamed": { description: "Repository renamed", category: "admin" },
  "repository.transferred": { description: "Repository transferred", category: "admin" },
  "repository.unarchived": { description: "Repository unarchived", category: "admin" },
  "repository_dispatch": { description: "Repository Dispatch", category: "automation" },
  "repository_import": { description: "Repository Import", category: "admin" },
  "repository_vulnerability_alert": { description: "Repository Vulnerability Alert", category: "security" },
  "repository_vulnerability_alert.create": { description: "Repository Vulnerability Alert create", category: "security" },
  "repository_vulnerability_alert.dismiss": { description: "Repository Vulnerability Alert dismiss", category: "security" },
  "repository_vulnerability_alert.reopen": { description: "Repository Vulnerability Alert reopen", category: "security" },
  "repository_vulnerability_alert.resolve": { description: "Repository Vulnerability Alert resolve", category: "security" },
  "secret_scanning_alert": { description: "Secret Scanning Alert", category: "security" },
  "secret_scanning_alert.created": { description: "Secret Scanning Alert created", category: "security" },
  "secret_scanning_alert.reopened": { description: "Secret Scanning Alert reopened", category: "security" },
  "secret_scanning_alert.resolved": { description: "Secret Scanning Alert resolved", category: "security" },
  "secret_scanning_alert.revoked": { description: "Secret Scanning Alert revoked", category: "security" },
  "secret_scanning_alert_location": { description: "Secret Scanning Alert Location", category: "security" },
  "secret_scanning_alert_location.created": { description: "Secret Scanning Alert Location created", category: "security" },
  "security_advisory": { description: "Security Advisory", category: "security" },
  "security_advisory.performed": { description: "Security Advisory performed", category: "security" },
  "security_advisory.published": { description: "Security Advisory published", category: "security" },
  "security_advisory.updated": { description: "Security Advisory updated", category: "security" },
  "security_advisory.withdrawn": { description: "Security Advisory withdrawn", category: "security" },
  "sponsorship": { description: "Sponsorship", category: "social" },
  "sponsorship.cancelled": { description: "Sponsorship cancelled", category: "social" },
  "sponsorship.created": { description: "Sponsorship created", category: "social" },
  "sponsorship.edited": { description: "Sponsorship edited", category: "social" },
  "sponsorship.pending_cancellation": { description: "Sponsorship pending cancellation", category: "social" },
  "sponsorship.pending_tier_change": { description: "Sponsorship pending tier change", category: "social" },
  "sponsorship.tier_changed": { description: "Sponsorship tier changed", category: "social" },
  "star": { description: "Star", category: "social" },
  "star.created": { description: "Star created", category: "social" },
  "star.deleted": { description: "Star deleted", category: "social" },
  "status": { description: "Status", category: "ci" },
  "team": { description: "Team", category: "admin" },
  "team.added_to_repository": { description: "Team added to repository", category: "admin" },
  "team.created": { description: "Team created", category: "admin" },
  "team.deleted": { description: "Team deleted", category: "admin" },
  "team.edited": { description: "Team edited", category: "admin" },
  "team.removed_from_repository": { description: "Team removed from repository", category: "admin" },
  "team_add": { description: "Team Add", category: "admin" },
  "watch": { description: "Watch", category: "social" },
  "watch.started": { description: "Watch started", category: "social" },
  "workflow_dispatch": { description: "Workflow Dispatch", category: "ci" },
  "workflow_job": { description: "Workflow Job", category: "ci" },
  "workflow_job.completed": { description: "Workflow Job completed", category: "ci" },
  "workflow_job.in_progress": { description: "Workflow Job in progress", category: "ci" },
  "workflow_job.queued": { description: "Workflow Job queued", category: "ci" },
  "workflow_job.waiting": { description: "Workflow Job waiting", category: "ci" },
  "workflow_run": { description: "Workflow Run", category: "ci" },
  "workflow_run.completed": { description: "Workflow Run completed", category: "ci" },
  "workflow_run.in_progress": { description: "Workflow Run in progress", category: "ci" },
  "workflow_run.requested": { description: "Workflow Run requested", category: "ci" },
};
