// AUTO-GENERATED — do not edit manually.
// Source: stripe@20.4.1 WebhookEndpointCreateParams.EnabledEvent
// Generated: 2026-03-18
// Regenerate: pnpm gen:stripe

import type { EventDefinition } from "../define";

export const stripeEventTypes = [
  "account.application.authorized",
  "account.application.deauthorized",
  "account.external_account.created",
  "account.external_account.deleted",
  "account.external_account.updated",
  "account.updated",
  "application_fee.created",
  "application_fee.refund.updated",
  "application_fee.refunded",
  "balance.available",
  "balance_settings.updated",
  "billing.alert.triggered",
  "billing.credit_balance_transaction.created",
  "billing.credit_grant.created",
  "billing.credit_grant.updated",
  "billing.meter.created",
  "billing.meter.deactivated",
  "billing.meter.reactivated",
  "billing.meter.updated",
  "billing_portal.configuration.created",
  "billing_portal.configuration.updated",
  "billing_portal.session.created",
  "capability.updated",
  "cash_balance.funds_available",
  "charge.captured",
  "charge.dispute.closed",
  "charge.dispute.created",
  "charge.dispute.funds_reinstated",
  "charge.dispute.funds_withdrawn",
  "charge.dispute.updated",
  "charge.expired",
  "charge.failed",
  "charge.pending",
  "charge.refund.updated",
  "charge.refunded",
  "charge.succeeded",
  "charge.updated",
  "checkout.session.async_payment_failed",
  "checkout.session.async_payment_succeeded",
  "checkout.session.completed",
  "checkout.session.expired",
  "climate.order.canceled",
  "climate.order.created",
  "climate.order.delayed",
  "climate.order.delivered",
  "climate.order.product_substituted",
  "climate.product.created",
  "climate.product.pricing_updated",
  "coupon.created",
  "coupon.deleted",
  "coupon.updated",
  "credit_note.created",
  "credit_note.updated",
  "credit_note.voided",
  "customer.created",
  "customer.deleted",
  "customer.discount.created",
  "customer.discount.deleted",
  "customer.discount.updated",
  "customer.source.created",
  "customer.source.deleted",
  "customer.source.expiring",
  "customer.source.updated",
  "customer.subscription.created",
  "customer.subscription.deleted",
  "customer.subscription.paused",
  "customer.subscription.pending_update_applied",
  "customer.subscription.pending_update_expired",
  "customer.subscription.resumed",
  "customer.subscription.trial_will_end",
  "customer.subscription.updated",
  "customer.tax_id.created",
  "customer.tax_id.deleted",
  "customer.tax_id.updated",
  "customer.updated",
  "customer_cash_balance_transaction.created",
  "entitlements.active_entitlement_summary.updated",
  "file.created",
  "financial_connections.account.account_numbers_updated",
  "financial_connections.account.created",
  "financial_connections.account.deactivated",
  "financial_connections.account.disconnected",
  "financial_connections.account.reactivated",
  "financial_connections.account.refreshed_balance",
  "financial_connections.account.refreshed_ownership",
  "financial_connections.account.refreshed_transactions",
  "financial_connections.account.upcoming_account_number_expiry",
  "identity.verification_session.canceled",
  "identity.verification_session.created",
  "identity.verification_session.processing",
  "identity.verification_session.redacted",
  "identity.verification_session.requires_input",
  "identity.verification_session.verified",
  "invoice.created",
  "invoice.deleted",
  "invoice.finalization_failed",
  "invoice.finalized",
  "invoice.marked_uncollectible",
  "invoice.overdue",
  "invoice.overpaid",
  "invoice.paid",
  "invoice.payment_action_required",
  "invoice.payment_attempt_required",
  "invoice.payment_failed",
  "invoice.payment_succeeded",
  "invoice.sent",
  "invoice.upcoming",
  "invoice.updated",
  "invoice.voided",
  "invoice.will_be_due",
  "invoice_payment.paid",
  "invoiceitem.created",
  "invoiceitem.deleted",
  "issuing_authorization.created",
  "issuing_authorization.request",
  "issuing_authorization.updated",
  "issuing_card.created",
  "issuing_card.updated",
  "issuing_cardholder.created",
  "issuing_cardholder.updated",
  "issuing_dispute.closed",
  "issuing_dispute.created",
  "issuing_dispute.funds_reinstated",
  "issuing_dispute.funds_rescinded",
  "issuing_dispute.submitted",
  "issuing_dispute.updated",
  "issuing_personalization_design.activated",
  "issuing_personalization_design.deactivated",
  "issuing_personalization_design.rejected",
  "issuing_personalization_design.updated",
  "issuing_token.created",
  "issuing_token.updated",
  "issuing_transaction.created",
  "issuing_transaction.purchase_details_receipt_updated",
  "issuing_transaction.updated",
  "mandate.updated",
  "payment_intent.amount_capturable_updated",
  "payment_intent.canceled",
  "payment_intent.created",
  "payment_intent.partially_funded",
  "payment_intent.payment_failed",
  "payment_intent.processing",
  "payment_intent.requires_action",
  "payment_intent.succeeded",
  "payment_link.created",
  "payment_link.updated",
  "payment_method.attached",
  "payment_method.automatically_updated",
  "payment_method.detached",
  "payment_method.updated",
  "payout.canceled",
  "payout.created",
  "payout.failed",
  "payout.paid",
  "payout.reconciliation_completed",
  "payout.updated",
  "person.created",
  "person.deleted",
  "person.updated",
  "plan.created",
  "plan.deleted",
  "plan.updated",
  "price.created",
  "price.deleted",
  "price.updated",
  "product.created",
  "product.deleted",
  "product.updated",
  "promotion_code.created",
  "promotion_code.updated",
  "quote.accepted",
  "quote.canceled",
  "quote.created",
  "quote.finalized",
  "radar.early_fraud_warning.created",
  "radar.early_fraud_warning.updated",
  "refund.created",
  "refund.failed",
  "refund.updated",
  "reporting.report_run.failed",
  "reporting.report_run.succeeded",
  "reporting.report_type.updated",
  "reserve.hold.created",
  "reserve.hold.updated",
  "reserve.plan.created",
  "reserve.plan.disabled",
  "reserve.plan.expired",
  "reserve.plan.updated",
  "reserve.release.created",
  "review.closed",
  "review.opened",
  "setup_intent.canceled",
  "setup_intent.created",
  "setup_intent.requires_action",
  "setup_intent.setup_failed",
  "setup_intent.succeeded",
  "sigma.scheduled_query_run.created",
  "source.canceled",
  "source.chargeable",
  "source.failed",
  "source.mandate_notification",
  "source.refund_attributes_required",
  "source.transaction.created",
  "source.transaction.updated",
  "subscription_schedule.aborted",
  "subscription_schedule.canceled",
  "subscription_schedule.completed",
  "subscription_schedule.created",
  "subscription_schedule.expiring",
  "subscription_schedule.released",
  "subscription_schedule.updated",
  "tax.settings.updated",
  "tax_rate.created",
  "tax_rate.updated",
  "terminal.reader.action_failed",
  "terminal.reader.action_succeeded",
  "terminal.reader.action_updated",
  "test_helpers.test_clock.advancing",
  "test_helpers.test_clock.created",
  "test_helpers.test_clock.deleted",
  "test_helpers.test_clock.internal_failure",
  "test_helpers.test_clock.ready",
  "topup.canceled",
  "topup.created",
  "topup.failed",
  "topup.reversed",
  "topup.succeeded",
  "transfer.created",
  "transfer.reversed",
  "transfer.updated",
  "treasury.credit_reversal.created",
  "treasury.credit_reversal.posted",
  "treasury.debit_reversal.completed",
  "treasury.debit_reversal.created",
  "treasury.debit_reversal.initial_credit_granted",
  "treasury.financial_account.closed",
  "treasury.financial_account.created",
  "treasury.financial_account.features_status_updated",
  "treasury.inbound_transfer.canceled",
  "treasury.inbound_transfer.created",
  "treasury.inbound_transfer.failed",
  "treasury.inbound_transfer.succeeded",
  "treasury.outbound_payment.canceled",
  "treasury.outbound_payment.created",
  "treasury.outbound_payment.expected_arrival_date_updated",
  "treasury.outbound_payment.failed",
  "treasury.outbound_payment.posted",
  "treasury.outbound_payment.returned",
  "treasury.outbound_payment.tracking_details_updated",
  "treasury.outbound_transfer.canceled",
  "treasury.outbound_transfer.created",
  "treasury.outbound_transfer.expected_arrival_date_updated",
  "treasury.outbound_transfer.failed",
  "treasury.outbound_transfer.posted",
  "treasury.outbound_transfer.returned",
  "treasury.outbound_transfer.tracking_details_updated",
  "treasury.received_credit.created",
  "treasury.received_credit.failed",
  "treasury.received_credit.succeeded",
  "treasury.received_debit.created",
] as const;

export type StripeEventType = (typeof stripeEventTypes)[number];

/** Auto-generated base descriptions. Hand-curated entries in stripe/index.ts override these. */
export const generatedStripeEvents: Record<StripeEventType, string | EventDefinition> = {
  "account.application.authorized": { description: "Account Application Authorized", category: "account" },
  "account.application.deauthorized": { description: "Account Application Deauthorized", category: "account" },
  "account.external_account.created": { description: "Account External Account Created", category: "account" },
  "account.external_account.deleted": { description: "Account External Account Deleted", category: "account" },
  "account.external_account.updated": { description: "Account External Account Updated", category: "account" },
  "account.updated": { description: "Account Updated", category: "account" },
  "application_fee.created": { description: "Application Fee Created", category: "connect" },
  "application_fee.refund.updated": { description: "Application Fee Refund Updated", category: "connect" },
  "application_fee.refunded": { description: "Application Fee Refunded", category: "connect" },
  "balance.available": { description: "Balance Available", category: "balance" },
  "balance_settings.updated": { description: "Balance Settings Updated", category: "balance" },
  "billing.alert.triggered": { description: "Billing Alert Triggered", category: "billing" },
  "billing.credit_balance_transaction.created": { description: "Billing Credit Balance Transaction Created", category: "billing" },
  "billing.credit_grant.created": { description: "Billing Credit Grant Created", category: "billing" },
  "billing.credit_grant.updated": { description: "Billing Credit Grant Updated", category: "billing" },
  "billing.meter.created": { description: "Billing Meter Created", category: "billing" },
  "billing.meter.deactivated": { description: "Billing Meter Deactivated", category: "billing" },
  "billing.meter.reactivated": { description: "Billing Meter Reactivated", category: "billing" },
  "billing.meter.updated": { description: "Billing Meter Updated", category: "billing" },
  "billing_portal.configuration.created": { description: "Billing Portal Configuration Created", category: "billing" },
  "billing_portal.configuration.updated": { description: "Billing Portal Configuration Updated", category: "billing" },
  "billing_portal.session.created": { description: "Billing Portal Session Created", category: "billing" },
  "capability.updated": { description: "Capability Updated", category: "connect" },
  "cash_balance.funds_available": { description: "Cash Balance Funds Available", category: "balance" },
  "charge.captured": { description: "Charge Captured", category: "payments" },
  "charge.dispute.closed": { description: "Charge Dispute Closed", category: "payments" },
  "charge.dispute.created": { description: "Charge Dispute Created", category: "payments" },
  "charge.dispute.funds_reinstated": { description: "Charge Dispute Funds Reinstated", category: "payments" },
  "charge.dispute.funds_withdrawn": { description: "Charge Dispute Funds Withdrawn", category: "payments" },
  "charge.dispute.updated": { description: "Charge Dispute Updated", category: "payments" },
  "charge.expired": { description: "Charge Expired", category: "payments" },
  "charge.failed": { description: "Charge Failed", category: "payments" },
  "charge.pending": { description: "Charge Pending", category: "payments" },
  "charge.refund.updated": { description: "Charge Refund Updated", category: "payments" },
  "charge.refunded": { description: "Charge Refunded", category: "payments" },
  "charge.succeeded": { description: "Charge Succeeded", category: "payments" },
  "charge.updated": { description: "Charge Updated", category: "payments" },
  "checkout.session.async_payment_failed": { description: "Checkout Session Async Payment Failed", category: "checkout" },
  "checkout.session.async_payment_succeeded": { description: "Checkout Session Async Payment Succeeded", category: "checkout" },
  "checkout.session.completed": { description: "Checkout Session Completed", category: "checkout" },
  "checkout.session.expired": { description: "Checkout Session Expired", category: "checkout" },
  "climate.order.canceled": { description: "Climate Order Canceled", category: "climate" },
  "climate.order.created": { description: "Climate Order Created", category: "climate" },
  "climate.order.delayed": { description: "Climate Order Delayed", category: "climate" },
  "climate.order.delivered": { description: "Climate Order Delivered", category: "climate" },
  "climate.order.product_substituted": { description: "Climate Order Product Substituted", category: "climate" },
  "climate.product.created": { description: "Climate Product Created", category: "climate" },
  "climate.product.pricing_updated": { description: "Climate Product Pricing Updated", category: "climate" },
  "coupon.created": { description: "Coupon Created", category: "billing" },
  "coupon.deleted": { description: "Coupon Deleted", category: "billing" },
  "coupon.updated": { description: "Coupon Updated", category: "billing" },
  "credit_note.created": { description: "Credit Note Created", category: "billing" },
  "credit_note.updated": { description: "Credit Note Updated", category: "billing" },
  "credit_note.voided": { description: "Credit Note Voided", category: "billing" },
  "customer.created": { description: "Customer Created", category: "customers" },
  "customer.deleted": { description: "Customer Deleted", category: "customers" },
  "customer.discount.created": { description: "Customer Discount Created", category: "customers" },
  "customer.discount.deleted": { description: "Customer Discount Deleted", category: "customers" },
  "customer.discount.updated": { description: "Customer Discount Updated", category: "customers" },
  "customer.source.created": { description: "Customer Source Created", category: "customers" },
  "customer.source.deleted": { description: "Customer Source Deleted", category: "customers" },
  "customer.source.expiring": { description: "Customer Source Expiring", category: "customers" },
  "customer.source.updated": { description: "Customer Source Updated", category: "customers" },
  "customer.subscription.created": { description: "Customer Subscription Created", category: "customers" },
  "customer.subscription.deleted": { description: "Customer Subscription Deleted", category: "customers" },
  "customer.subscription.paused": { description: "Customer Subscription Paused", category: "customers" },
  "customer.subscription.pending_update_applied": { description: "Customer Subscription Pending Update Applied", category: "customers" },
  "customer.subscription.pending_update_expired": { description: "Customer Subscription Pending Update Expired", category: "customers" },
  "customer.subscription.resumed": { description: "Customer Subscription Resumed", category: "customers" },
  "customer.subscription.trial_will_end": { description: "Customer Subscription Trial Will End", category: "customers" },
  "customer.subscription.updated": { description: "Customer Subscription Updated", category: "customers" },
  "customer.tax_id.created": { description: "Customer Tax Id Created", category: "customers" },
  "customer.tax_id.deleted": { description: "Customer Tax Id Deleted", category: "customers" },
  "customer.tax_id.updated": { description: "Customer Tax Id Updated", category: "customers" },
  "customer.updated": { description: "Customer Updated", category: "customers" },
  "customer_cash_balance_transaction.created": { description: "Customer Cash Balance Transaction Created", category: "customers" },
  "entitlements.active_entitlement_summary.updated": { description: "Entitlements Active Entitlement Summary Updated", category: "entitlements" },
  "file.created": { description: "File Created", category: "files" },
  "financial_connections.account.account_numbers_updated": { description: "Financial Connections Account Account Numbers Updated", category: "financial_connections" },
  "financial_connections.account.created": { description: "Financial Connections Account Created", category: "financial_connections" },
  "financial_connections.account.deactivated": { description: "Financial Connections Account Deactivated", category: "financial_connections" },
  "financial_connections.account.disconnected": { description: "Financial Connections Account Disconnected", category: "financial_connections" },
  "financial_connections.account.reactivated": { description: "Financial Connections Account Reactivated", category: "financial_connections" },
  "financial_connections.account.refreshed_balance": { description: "Financial Connections Account Refreshed Balance", category: "financial_connections" },
  "financial_connections.account.refreshed_ownership": { description: "Financial Connections Account Refreshed Ownership", category: "financial_connections" },
  "financial_connections.account.refreshed_transactions": { description: "Financial Connections Account Refreshed Transactions", category: "financial_connections" },
  "financial_connections.account.upcoming_account_number_expiry": { description: "Financial Connections Account Upcoming Account Number Expiry", category: "financial_connections" },
  "identity.verification_session.canceled": { description: "Identity Verification Session Canceled", category: "identity" },
  "identity.verification_session.created": { description: "Identity Verification Session Created", category: "identity" },
  "identity.verification_session.processing": { description: "Identity Verification Session Processing", category: "identity" },
  "identity.verification_session.redacted": { description: "Identity Verification Session Redacted", category: "identity" },
  "identity.verification_session.requires_input": { description: "Identity Verification Session Requires Input", category: "identity" },
  "identity.verification_session.verified": { description: "Identity Verification Session Verified", category: "identity" },
  "invoice.created": { description: "Invoice Created", category: "billing" },
  "invoice.deleted": { description: "Invoice Deleted", category: "billing" },
  "invoice.finalization_failed": { description: "Invoice Finalization Failed", category: "billing" },
  "invoice.finalized": { description: "Invoice Finalized", category: "billing" },
  "invoice.marked_uncollectible": { description: "Invoice Marked Uncollectible", category: "billing" },
  "invoice.overdue": { description: "Invoice Overdue", category: "billing" },
  "invoice.overpaid": { description: "Invoice Overpaid", category: "billing" },
  "invoice.paid": { description: "Invoice Paid", category: "billing" },
  "invoice.payment_action_required": { description: "Invoice Payment Action Required", category: "billing" },
  "invoice.payment_attempt_required": { description: "Invoice Payment Attempt Required", category: "billing" },
  "invoice.payment_failed": { description: "Invoice Payment Failed", category: "billing" },
  "invoice.payment_succeeded": { description: "Invoice Payment Succeeded", category: "billing" },
  "invoice.sent": { description: "Invoice Sent", category: "billing" },
  "invoice.upcoming": { description: "Invoice Upcoming", category: "billing" },
  "invoice.updated": { description: "Invoice Updated", category: "billing" },
  "invoice.voided": { description: "Invoice Voided", category: "billing" },
  "invoice.will_be_due": { description: "Invoice Will Be Due", category: "billing" },
  "invoice_payment.paid": { description: "Invoice Payment Paid", category: "other" },
  "invoiceitem.created": { description: "Invoiceitem Created", category: "billing" },
  "invoiceitem.deleted": { description: "Invoiceitem Deleted", category: "billing" },
  "issuing_authorization.created": { description: "Issuing Authorization Created", category: "other" },
  "issuing_authorization.request": { description: "Issuing Authorization Request", category: "other" },
  "issuing_authorization.updated": { description: "Issuing Authorization Updated", category: "other" },
  "issuing_card.created": { description: "Issuing Card Created", category: "other" },
  "issuing_card.updated": { description: "Issuing Card Updated", category: "other" },
  "issuing_cardholder.created": { description: "Issuing Cardholder Created", category: "other" },
  "issuing_cardholder.updated": { description: "Issuing Cardholder Updated", category: "other" },
  "issuing_dispute.closed": { description: "Issuing Dispute Closed", category: "other" },
  "issuing_dispute.created": { description: "Issuing Dispute Created", category: "other" },
  "issuing_dispute.funds_reinstated": { description: "Issuing Dispute Funds Reinstated", category: "other" },
  "issuing_dispute.funds_rescinded": { description: "Issuing Dispute Funds Rescinded", category: "other" },
  "issuing_dispute.submitted": { description: "Issuing Dispute Submitted", category: "other" },
  "issuing_dispute.updated": { description: "Issuing Dispute Updated", category: "other" },
  "issuing_personalization_design.activated": { description: "Issuing Personalization Design Activated", category: "other" },
  "issuing_personalization_design.deactivated": { description: "Issuing Personalization Design Deactivated", category: "other" },
  "issuing_personalization_design.rejected": { description: "Issuing Personalization Design Rejected", category: "other" },
  "issuing_personalization_design.updated": { description: "Issuing Personalization Design Updated", category: "other" },
  "issuing_token.created": { description: "Issuing Token Created", category: "other" },
  "issuing_token.updated": { description: "Issuing Token Updated", category: "other" },
  "issuing_transaction.created": { description: "Issuing Transaction Created", category: "other" },
  "issuing_transaction.purchase_details_receipt_updated": { description: "Issuing Transaction Purchase Details Receipt Updated", category: "other" },
  "issuing_transaction.updated": { description: "Issuing Transaction Updated", category: "other" },
  "mandate.updated": { description: "Mandate Updated", category: "payments" },
  "payment_intent.amount_capturable_updated": { description: "Payment Intent Amount Capturable Updated", category: "payments" },
  "payment_intent.canceled": { description: "Payment Intent Canceled", category: "payments" },
  "payment_intent.created": { description: "Payment Intent Created", category: "payments" },
  "payment_intent.partially_funded": { description: "Payment Intent Partially Funded", category: "payments" },
  "payment_intent.payment_failed": { description: "Payment Intent Payment Failed", category: "payments" },
  "payment_intent.processing": { description: "Payment Intent Processing", category: "payments" },
  "payment_intent.requires_action": { description: "Payment Intent Requires Action", category: "payments" },
  "payment_intent.succeeded": { description: "Payment Intent Succeeded", category: "payments" },
  "payment_link.created": { description: "Payment Link Created", category: "payments" },
  "payment_link.updated": { description: "Payment Link Updated", category: "payments" },
  "payment_method.attached": { description: "Payment Method Attached", category: "payments" },
  "payment_method.automatically_updated": { description: "Payment Method Automatically Updated", category: "payments" },
  "payment_method.detached": { description: "Payment Method Detached", category: "payments" },
  "payment_method.updated": { description: "Payment Method Updated", category: "payments" },
  "payout.canceled": { description: "Payout Canceled", category: "payouts" },
  "payout.created": { description: "Payout Created", category: "payouts" },
  "payout.failed": { description: "Payout Failed", category: "payouts" },
  "payout.paid": { description: "Payout Paid", category: "payouts" },
  "payout.reconciliation_completed": { description: "Payout Reconciliation Completed", category: "payouts" },
  "payout.updated": { description: "Payout Updated", category: "payouts" },
  "person.created": { description: "Person Created", category: "connect" },
  "person.deleted": { description: "Person Deleted", category: "connect" },
  "person.updated": { description: "Person Updated", category: "connect" },
  "plan.created": { description: "Plan Created", category: "billing" },
  "plan.deleted": { description: "Plan Deleted", category: "billing" },
  "plan.updated": { description: "Plan Updated", category: "billing" },
  "price.created": { description: "Price Created", category: "billing" },
  "price.deleted": { description: "Price Deleted", category: "billing" },
  "price.updated": { description: "Price Updated", category: "billing" },
  "product.created": { description: "Product Created", category: "products" },
  "product.deleted": { description: "Product Deleted", category: "products" },
  "product.updated": { description: "Product Updated", category: "products" },
  "promotion_code.created": { description: "Promotion Code Created", category: "billing" },
  "promotion_code.updated": { description: "Promotion Code Updated", category: "billing" },
  "quote.accepted": { description: "Quote Accepted", category: "billing" },
  "quote.canceled": { description: "Quote Canceled", category: "billing" },
  "quote.created": { description: "Quote Created", category: "billing" },
  "quote.finalized": { description: "Quote Finalized", category: "billing" },
  "radar.early_fraud_warning.created": { description: "Radar Early Fraud Warning Created", category: "fraud" },
  "radar.early_fraud_warning.updated": { description: "Radar Early Fraud Warning Updated", category: "fraud" },
  "refund.created": { description: "Refund Created", category: "payments" },
  "refund.failed": { description: "Refund Failed", category: "payments" },
  "refund.updated": { description: "Refund Updated", category: "payments" },
  "reporting.report_run.failed": { description: "Reporting Report Run Failed", category: "reporting" },
  "reporting.report_run.succeeded": { description: "Reporting Report Run Succeeded", category: "reporting" },
  "reporting.report_type.updated": { description: "Reporting Report Type Updated", category: "reporting" },
  "reserve.hold.created": { description: "Reserve Hold Created", category: "other" },
  "reserve.hold.updated": { description: "Reserve Hold Updated", category: "other" },
  "reserve.plan.created": { description: "Reserve Plan Created", category: "other" },
  "reserve.plan.disabled": { description: "Reserve Plan Disabled", category: "other" },
  "reserve.plan.expired": { description: "Reserve Plan Expired", category: "other" },
  "reserve.plan.updated": { description: "Reserve Plan Updated", category: "other" },
  "reserve.release.created": { description: "Reserve Release Created", category: "other" },
  "review.closed": { description: "Review Closed", category: "fraud" },
  "review.opened": { description: "Review Opened", category: "fraud" },
  "setup_intent.canceled": { description: "Setup Intent Canceled", category: "payments" },
  "setup_intent.created": { description: "Setup Intent Created", category: "payments" },
  "setup_intent.requires_action": { description: "Setup Intent Requires Action", category: "payments" },
  "setup_intent.setup_failed": { description: "Setup Intent Setup Failed", category: "payments" },
  "setup_intent.succeeded": { description: "Setup Intent Succeeded", category: "payments" },
  "sigma.scheduled_query_run.created": { description: "Sigma Scheduled Query Run Created", category: "reporting" },
  "source.canceled": { description: "Source Canceled", category: "payments" },
  "source.chargeable": { description: "Source Chargeable", category: "payments" },
  "source.failed": { description: "Source Failed", category: "payments" },
  "source.mandate_notification": { description: "Source Mandate Notification", category: "payments" },
  "source.refund_attributes_required": { description: "Source Refund Attributes Required", category: "payments" },
  "source.transaction.created": { description: "Source Transaction Created", category: "payments" },
  "source.transaction.updated": { description: "Source Transaction Updated", category: "payments" },
  "subscription_schedule.aborted": { description: "Subscription Schedule Aborted", category: "billing" },
  "subscription_schedule.canceled": { description: "Subscription Schedule Canceled", category: "billing" },
  "subscription_schedule.completed": { description: "Subscription Schedule Completed", category: "billing" },
  "subscription_schedule.created": { description: "Subscription Schedule Created", category: "billing" },
  "subscription_schedule.expiring": { description: "Subscription Schedule Expiring", category: "billing" },
  "subscription_schedule.released": { description: "Subscription Schedule Released", category: "billing" },
  "subscription_schedule.updated": { description: "Subscription Schedule Updated", category: "billing" },
  "tax.settings.updated": { description: "Tax Settings Updated", category: "tax" },
  "tax_rate.created": { description: "Tax Rate Created", category: "tax" },
  "tax_rate.updated": { description: "Tax Rate Updated", category: "tax" },
  "terminal.reader.action_failed": { description: "Terminal Reader Action Failed", category: "terminal" },
  "terminal.reader.action_succeeded": { description: "Terminal Reader Action Succeeded", category: "terminal" },
  "terminal.reader.action_updated": { description: "Terminal Reader Action Updated", category: "terminal" },
  "test_helpers.test_clock.advancing": { description: "Test Helpers Test Clock Advancing", category: "testing" },
  "test_helpers.test_clock.created": { description: "Test Helpers Test Clock Created", category: "testing" },
  "test_helpers.test_clock.deleted": { description: "Test Helpers Test Clock Deleted", category: "testing" },
  "test_helpers.test_clock.internal_failure": { description: "Test Helpers Test Clock Internal Failure", category: "testing" },
  "test_helpers.test_clock.ready": { description: "Test Helpers Test Clock Ready", category: "testing" },
  "topup.canceled": { description: "Topup Canceled", category: "balance" },
  "topup.created": { description: "Topup Created", category: "balance" },
  "topup.failed": { description: "Topup Failed", category: "balance" },
  "topup.reversed": { description: "Topup Reversed", category: "balance" },
  "topup.succeeded": { description: "Topup Succeeded", category: "balance" },
  "transfer.created": { description: "Transfer Created", category: "connect" },
  "transfer.reversed": { description: "Transfer Reversed", category: "connect" },
  "transfer.updated": { description: "Transfer Updated", category: "connect" },
  "treasury.credit_reversal.created": { description: "Treasury Credit Reversal Created", category: "treasury" },
  "treasury.credit_reversal.posted": { description: "Treasury Credit Reversal Posted", category: "treasury" },
  "treasury.debit_reversal.completed": { description: "Treasury Debit Reversal Completed", category: "treasury" },
  "treasury.debit_reversal.created": { description: "Treasury Debit Reversal Created", category: "treasury" },
  "treasury.debit_reversal.initial_credit_granted": { description: "Treasury Debit Reversal Initial Credit Granted", category: "treasury" },
  "treasury.financial_account.closed": { description: "Treasury Financial Account Closed", category: "treasury" },
  "treasury.financial_account.created": { description: "Treasury Financial Account Created", category: "treasury" },
  "treasury.financial_account.features_status_updated": { description: "Treasury Financial Account Features Status Updated", category: "treasury" },
  "treasury.inbound_transfer.canceled": { description: "Treasury Inbound Transfer Canceled", category: "treasury" },
  "treasury.inbound_transfer.created": { description: "Treasury Inbound Transfer Created", category: "treasury" },
  "treasury.inbound_transfer.failed": { description: "Treasury Inbound Transfer Failed", category: "treasury" },
  "treasury.inbound_transfer.succeeded": { description: "Treasury Inbound Transfer Succeeded", category: "treasury" },
  "treasury.outbound_payment.canceled": { description: "Treasury Outbound Payment Canceled", category: "treasury" },
  "treasury.outbound_payment.created": { description: "Treasury Outbound Payment Created", category: "treasury" },
  "treasury.outbound_payment.expected_arrival_date_updated": { description: "Treasury Outbound Payment Expected Arrival Date Updated", category: "treasury" },
  "treasury.outbound_payment.failed": { description: "Treasury Outbound Payment Failed", category: "treasury" },
  "treasury.outbound_payment.posted": { description: "Treasury Outbound Payment Posted", category: "treasury" },
  "treasury.outbound_payment.returned": { description: "Treasury Outbound Payment Returned", category: "treasury" },
  "treasury.outbound_payment.tracking_details_updated": { description: "Treasury Outbound Payment Tracking Details Updated", category: "treasury" },
  "treasury.outbound_transfer.canceled": { description: "Treasury Outbound Transfer Canceled", category: "treasury" },
  "treasury.outbound_transfer.created": { description: "Treasury Outbound Transfer Created", category: "treasury" },
  "treasury.outbound_transfer.expected_arrival_date_updated": { description: "Treasury Outbound Transfer Expected Arrival Date Updated", category: "treasury" },
  "treasury.outbound_transfer.failed": { description: "Treasury Outbound Transfer Failed", category: "treasury" },
  "treasury.outbound_transfer.posted": { description: "Treasury Outbound Transfer Posted", category: "treasury" },
  "treasury.outbound_transfer.returned": { description: "Treasury Outbound Transfer Returned", category: "treasury" },
  "treasury.outbound_transfer.tracking_details_updated": { description: "Treasury Outbound Transfer Tracking Details Updated", category: "treasury" },
  "treasury.received_credit.created": { description: "Treasury Received Credit Created", category: "treasury" },
  "treasury.received_credit.failed": { description: "Treasury Received Credit Failed", category: "treasury" },
  "treasury.received_credit.succeeded": { description: "Treasury Received Credit Succeeded", category: "treasury" },
  "treasury.received_debit.created": { description: "Treasury Received Debit Created", category: "treasury" },
};
